name: my_flutter_plugin_android
description: Android implementation of the my_flutter_plugin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: my_flutter_plugin
    platforms:
      android:
        package: com.example.verygoodcore
        pluginClass: MyFlutterPluginPlugin
        dartPluginClass: MyFlutterPluginAndroid

dependencies:
  flutter:
    sdk: flutter
  my_flutter_plugin_platform_interface:
    path: ../my_flutter_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
