name: my_flutter_plugin
description: My new Flutter plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: my_flutter_plugin_android
      ios:
        default_package: my_flutter_plugin_ios

dependencies:
  flutter:
    sdk: flutter
  my_flutter_plugin_android:
    path: ../my_flutter_plugin_android
  my_flutter_plugin_ios:
    path: ../my_flutter_plugin_ios
  my_flutter_plugin_platform_interface:
    path: ../my_flutter_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
